export const DATA = {
  chefs: [
    {
      id: 'sanjyot',
      name: 'Sanjyot Keer',
      handle: 'Your Food Lab',
      avatar: 'oklch(0.55 0.12 35)',
      bio: 'Three-time James Beard nominee. Cooks like your khansama, films like a poet.',
      brands: ['Tata Sampann', 'MDH', 'Amul', 'Mother Dairy'],
      heroTint: 'oklch(0.32 0.08 35)',
    },
    {
      id: 'ranveer',
      name: 'Ranveer Brar',
      handle: 'Chef Ranveer',
      avatar: 'oklch(0.45 0.10 50)',
      bio: 'Masala roads & royal kitchens. Brings street food the discipline of a kitchen brigade.',
      brands: ['MDH', 'Fortune', 'Saffola'],
      heroTint: 'oklch(0.28 0.07 50)',
    },
    {
      id: 'hebbar',
      name: 'Archana',
      handle: "Hebbar's Kitchen",
      avatar: 'oklch(0.50 0.11 25)',
      bio: 'South Indian comfort, decoded. Step-by-step, never a dosa out of place.',
      brands: ['Aashirvaad', 'iD Fresh', 'Eastern'],
      heroTint: 'oklch(0.30 0.08 25)',
    },
    {
      id: 'nisha',
      name: 'Nisha Madhulika',
      handle: 'Nisha Madhulika',
      avatar: 'oklch(0.48 0.10 60)',
      bio: 'Vegetarian, vernacular, very precise. The internet aunt of Indian cooking.',
      brands: ['Tata Sampann', 'Dabur', 'Patanjali'],
      heroTint: 'oklch(0.30 0.08 60)',
    },
    {
      id: 'kabita',
      name: 'Kabita Singh',
      handle: "Kabita's Kitchen",
      avatar: 'oklch(0.52 0.11 15)',
      bio: 'Bachelor-friendly recipes that taste like you finally called your mother back.',
      brands: ['Fortune', 'MDH', 'Amul'],
      heroTint: 'oklch(0.30 0.08 15)',
    },
  ],

  recipes: [
    {
      id: 'pbm',
      title: 'Paneer Butter Masala',
      chef: 'sanjyot',
      time: '25 min',
      serves: 4,
      heat: 2,
      gradient: ['oklch(0.55 0.18 35)', 'oklch(0.35 0.14 25)'],
      reelHandle: '@yourfoodlab',
      reelDuration: '0:58',
    },
    {
      id: 'dosa',
      title: 'Crisp Masala Dosa',
      chef: 'hebbar',
      time: '40 min',
      serves: 3,
      heat: 1,
      gradient: ['oklch(0.60 0.10 80)', 'oklch(0.40 0.08 60)'],
      reelHandle: '@hebbarskitchen',
      reelDuration: '1:12',
    },
    {
      id: 'biryani',
      title: 'Lucknowi Mutton Biryani',
      chef: 'ranveer',
      time: '90 min',
      serves: 6,
      heat: 3,
      gradient: ['oklch(0.50 0.16 50)', 'oklch(0.30 0.10 30)'],
      reelHandle: '@ranveer.brar',
      reelDuration: '1:30',
    },
    {
      id: 'pao',
      title: 'Mumbai Pav Bhaji',
      chef: 'kabita',
      time: '35 min',
      serves: 4,
      heat: 2,
      gradient: ['oklch(0.52 0.15 25)', 'oklch(0.32 0.12 15)'],
      reelHandle: '@kabitaskitchen',
      reelDuration: '0:47',
    },
    {
      id: 'aloo',
      title: 'Aloo Paratha (Punjabi)',
      chef: 'nisha',
      time: '30 min',
      serves: 4,
      heat: 1,
      gradient: ['oklch(0.58 0.10 70)', 'oklch(0.38 0.08 50)'],
      reelHandle: '@nishamadhulika',
      reelDuration: '0:54',
    },
  ],

  pbmIngredients: [
    { id: 'paneer',   name: 'Paneer',               qty: '400 g',    size: '1 pack',     brand: 'Mother Dairy', chefPick: true,  price: 145, swatch: 'oklch(0.92 0.02 80)' },
    { id: 'tomatoes', name: 'Tomatoes',              qty: '500 g',    size: '1 kg pack',  brand: 'Fresh',        chefPick: false, price: 38,  swatch: 'oklch(0.55 0.20 25)' },
    { id: 'butter',   name: 'White Butter',          qty: '100 g',    size: '200 g block',brand: 'Amul',         chefPick: true,  price: 110, swatch: 'oklch(0.95 0.04 90)' },
    { id: 'cream',    name: 'Fresh Cream',           qty: '50 ml',    size: '200 ml pack',brand: 'Amul',         chefPick: true,  price: 75,  swatch: 'oklch(0.93 0.02 85)' },
    { id: 'cashew',   name: 'Cashew Nuts',           qty: '50 g',     size: '200 g pouch',brand: 'Happilo',      chefPick: false, price: 165, swatch: 'oklch(0.82 0.06 85)' },
    { id: 'ginger',   name: 'Ginger',                qty: '1 inch',   size: '100 g pack', brand: 'Fresh',        chefPick: false, price: 22,  swatch: 'oklch(0.78 0.06 70)' },
    { id: 'garlic',   name: 'Garlic',                qty: '6 cloves', size: '100 g pack', brand: 'Fresh',        chefPick: false, price: 28,  swatch: 'oklch(0.90 0.03 95)' },
    { id: 'chilli',   name: 'Kashmiri Chilli Powder',qty: '1 tsp',    size: '100 g jar',  brand: 'Tata Sampann', chefPick: true,  price: 95,  swatch: 'oklch(0.50 0.18 30)' },
    { id: 'garam',    name: 'Garam Masala',          qty: '½ tsp',    size: '100 g pack', brand: 'MDH',          chefPick: true,  price: 80,  swatch: 'oklch(0.40 0.10 50)' },
    { id: 'kasuri',   name: 'Kasuri Methi',          qty: '1 tbsp',   size: '25 g pack',  brand: 'Catch',        chefPick: false, price: 45,  swatch: 'oklch(0.55 0.10 130)' },
    { id: 'sugar',    name: 'Sugar',                 qty: '1 tsp',    size: '1 kg pack',  brand: 'Madhur',       chefPick: false, price: 52,  swatch: 'oklch(0.96 0.01 90)' },
    { id: 'kewra',    name: 'Kewra Water',           qty: '2 drops',  size: '30 ml bottle',brand: 'Dabur',       chefPick: false, unmatched: true, price: 0, swatch: 'oklch(0.85 0.04 130)' },
  ],

  paneerAlternatives: [
    { id: 'mother',   brand: 'Mother Dairy', size: '400 g', price: 145, rating: 4.5, chefPick: true,  swatch: 'oklch(0.92 0.02 80)' },
    { id: 'amul',     brand: 'Amul',         size: '400 g', price: 152, rating: 4.4, chefPick: false, swatch: 'oklch(0.94 0.03 85)' },
    { id: 'gowardhan',brand: 'Gowardhan',    size: '400 g', price: 138, rating: 4.2, chefPick: false, swatch: 'oklch(0.91 0.02 78)' },
    { id: 'milky',    brand: 'Milky Mist',   size: '400 g', price: 165, rating: 4.6, chefPick: false, swatch: 'oklch(0.93 0.03 82)' },
  ],

  savedRecipes: ['pbm', 'dosa', 'pao'],
  cookedRecipes: ['biryani'],
}
